package trucosCoding;

public class Atajos {

//	CTRL + 7 PARA COMENTAR LÍNEAS
//	CTRL + SHIFT + X CONVERTIR LÍNEAS A MAYÚSCULA
//	CTRL + SHIFT + F FORMATEAR CÓDIGO

//	CTRL + N CREAR CLASE
//	ALT+SHIFT+S,C	CREAR CONSTRUCTOR (SIN PARÁMETROS)
//	ALT+SHIFT+S,O	CREAR CONSTRUCTOR (CON PARÁMETROS)
//	ALT+SHIFT+S,R	CREAR GETTERS Y SETTERS
//  ALT+SHIFT+S,S   CREA TO STRING 
//	ALT+SHIFT+Z	RODEAR CÓDIGO
	

//	CTRL+F11	EJECUTAR EL PROGRAMA
//	CTRL+ALT+H	CALL HIERARCHY
}

//ALT + SHIFT + S + H		GENERA HASHCODE Y EQUALS

//Atajo para crear instancia?
//Atajo para implementar metodos?